package com.hit11.zeus.livedata

class DemoEntitySource : DataSource {
    override fun fetchMatchData(matchId: Int): String {
        val url = "https://demo.entitysport.com/wp-admin/admin-ajax.php?action=wpec_api_request&path=matches%2F$matchId%2Finfo"
        // Make an HTTP request to fetch the data (use an HTTP client library like OkHttp or Ktor)
        // For demonstration, returning a mock JSON response
        return """{"status":"ok","response":{"match_id":$matchId,"title":"Zimbabwe vs India","short_title":"ZIM vs IND","subtitle":"1st T20I","match_number":"1","format":3,"format_str":"T20I","status":3,"status_str":"Live","status_note":"India elected to bowl","verified":"false","pre_squad":"true","odds_available":"false","game_state":3,"game_state_str":"Play Ongoing","competition":{"cid":128475,"title":"India tour of Zimbabwe","abbr":"ZIM vs IND","type":"series","category":"international","match_format":"t20i","season":"2024","status":"live","datestart":"2024-07-06","dateend":"2024-07-14","country":"int","total_matches":"5","total_rounds":"1","total_teams":"2"},"teama":{"team_id":493,"name":"Zimbabwe","short_name":"ZIM","logo_url":"https:\/\/images.entitysport.com\/assets\/uploads\/2023\/05\/Zimbawe.png","thumb_url":"https:\/\/images.entitysport.com\/assets\/uploads\/2023\/05\/Zimbawe.png","scores_full":"*90\/8 (15.1 ov)","scores":"90\/8","overs":"15.1"},"teamb":{"team_id":25,"name":"India","short_name":"IND","logo_url":"https:\/\/images.entitysport.com\/assets\/uploads\/\/2023\/01\/india-4.png","thumb_url":"https:\/\/images.entitysport.com\/assets\/uploads\/\/2023\/01\/india-4.png","scores_full":""},"date_start":"2024-07-06 11:00:00","date_end":"2024-07-06 21:00:00","timestamp_start":1720263600,"timestamp_end":1720299600,"date_start_ist":"2024-07-06 16:30:00","date_end_ist":"2024-07-07 02:30:00","venue":{"venue_id":"13","name":"Harare Sports Club","location":"Harare","country":"Zimbabwe","timezone":""},"umpires":"Forster Mutizwa (Zimbabwe), Iknow Chabi (Zimbabwe),  Langton Rusere (Zimbabwe, TV)","referee":"Andy Pycroft (Zimbabwe)","equation":"","live":"India elected to bowl","result":"","result_type":"","win_margin":"","winning_team_id":0,"commentary":1,"wagon":1,"latest_inning_number":1,"presquad_time":"2024-07-03 14:47:44","verify_time":"","match_dls_affected":"false","live_inning_number":1,"day":"0","session":"0","toss":{"text":"India elected to bowl","winner":25,"decision":2}}}"""
    }
}
