# website/netlify.toml
[build]
command = "npm run build"
publish = ".next"
base = "website"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "18"

[[plugins]]
package = "@netlify/plugin-nextjs"